pom.xml
Signed-off-by: Tomas Kraus <tomas.kraus@oracle.com>
=> Added --pinentry-mode loopback to GPG configurartion.

LICENSE.md, jaxb-api/pom.xml, pom.xml
=> Fixes #79: bundle symbolic name should match artifactId

jaxb-api-test/pom.xml, jaxb-api/pom.xml, pom.xml
release branch can be deleted after merge.
=> Merge 2.3.2 release informartion into EE4J_8.

jaxb-api/src/main/java/javax/xml/bind/ModuleUtil.java, jaxb-api/src/main/mr-jar/javax/xml/bind/ModuleUtil.java
=> Prevent Java Compiler inlining of default ModuleUtil.DEFAULT_FACTORY_CLASS

CONTRIBUTING.md, NOTICE.md, README.md, jaxb-api/exclude.xml, jaxb-api/pom.xml, jaxb-api/src/main/java/javax/xml/bind/ModuleUtil.java, jaxb-api/src/main/mr-jar/javax/xml/bind/ModuleUtil.java, pom.xml
Fixes #95 
+ minor cleanup in poms (spotbugs, updated copyright plugin, ...)
=> #95: Change project name to Jakarta XML Binding

CONTRIBUTING.md, NOTICE.md, README.md, jaxb-api-test/pom.xml, jaxb-api/pom.xml, jaxb-api/src/main/java/javax/xml/bind/JAXBContext.java, jaxb-api/src/main/java/javax/xml/bind/Marshaller.java, jaxb-api/src/main/java/javax/xml/bind/Unmarshaller.java, jaxb-api/src/main/java/javax/xml/bind/Validator.java, jaxb-api/src/main/java/javax/xml/bind/annotation/XmlType.java, jaxb-api/src/main/java/javax/xml/bind/annotation/package-info.java, jaxb-api/src/main/java/module-info.java, jaxb-api/src/main/javadoc/doc-files/speclicense.html, pom.xml, spec/LICENSE, spec/pom.xml, spec/src/assembly/assembly.xml
* fixed javadoc
* added speclicense to javadoc jar
* skip spotbugs in tests
* fixed licenses
* updated readme
=> speclicense, javadoc

jaxb-api/src/main/java/module-info.java
=> tweak javadoc

spec/src/main/asciidoc/license-efsl.adoc
=> fix revmark

jaxb-api/pom.xml, spec/src/main/asciidoc/license-efsl.adoc
=> fix cp holder

etc/jenkins/release.groovy, etc/jenkins/release.sh
Job will be reconfigured after this is in master.
=> Removed specification artifacts from release job.

pom.xml
=> Integrate activation 1.2.2

jaxb-api/pom.xml, pom.xml
=> increase impl version

etc/jenkins/continuous.groovy, etc/jenkins/release.groovy
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
=> JIPP migration

jaxb-api-test/pom.xml, jaxb-api/pom.xml, pom.xml
=> update parent, plugins, remove timestamp

jaxb-api/pom.xml, jaxb-api/src/main/java/javax/xml/bind/JAXBContext.java, jaxb-api/src/main/java/javax/xml/bind/JAXBContextFactory.java, pom.xml
=> give javadoc SE 8 look

spec/pom.xml, spec/src/assembly/assembly.xml, spec/src/main/asciidoc/xml-binding-spec.adoc, spec/src/main/asciidoc/xml-binding.adoc
=> fix the spec name

jaxb-api/src/main/java/jakarta/xml/bind/JAXB.java, jaxb-api/src/main/java/module-info.java
=> remove direct dependency on java.desktop from the API

jaxb-api/pom.xml, pom.xml
=> integrate jakarta.activation 2.0.0-RC2

.travis.yml, README.md, jaxb-api/pom.xml, jaxb-api/src/main/java/jakarta/xml/bind/JAXBContext.java, jaxb-api/src/main/java/jakarta/xml/bind/annotation/XmlAccessorOrder.java, jaxb-api/src/main/java/jakarta/xml/bind/annotation/XmlAnyElement.java, jaxb-api/src/main/java/jakarta/xml/bind/annotation/XmlElementRef.java, jaxb-api/src/main/java/jakarta/xml/bind/annotation/XmlSchema.java, jaxb-api/src/main/java/jakarta/xml/bind/annotation/XmlType.java, pom.xml
=> update build plugins

jaxb-api/pom.xml, pom.xml
=> integrate activation 2.0.0-RC3

jaxb-api/src/main/resources/jakarta/xml/bind/bindingschema_1_0.xsd, jaxb-api/src/main/resources/jakarta/xml/bind/bindingschema_2_0.xsd, jaxb-api/src/main/resources/jakarta/xml/bind/bindingschema_3_0.xsd
=> add schemas

.gitignore
Signed-off-by: Thodoris Bais <thodoris.bais@gmail.com>
=> Added MacOSX related file types

spec/src/main/asciidoc/XMLBinding.adoc
Signed-off-by: Thodoris Bais <thodoris.bais@gmail.com>
=> Move spec files from javax.* to jakarta.* packages for Jakarta EE 9

CONTRIBUTING.md
=> #150: Update CONTRIBUTING.md for Specification Project's repositories

jaxb-api/pom.xml, pom.xml
=> Integrate activation 2.0.0

etc/jenkins/release.sh
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
=> fix release job according to eclipse requirements

spec/src/main/asciidoc/XMLBinding.adoc, spec/src/main/asciidoc/ch07-customize_xml_schema.adoc
Signed-off-by: tvallin <thibault.vallin@oracle.com>
=> Update chapter 7

spec/src/main/asciidoc/ch08-java_types.adoc
Signed-off-by: tvallin <thibault.vallin@oracle.com>
=> update chapter 8

spec/src/main/asciidoc/appE-external_binding.adoc, spec/src/main/asciidoc/ch01-introduction.adoc
=> use updated namespace

jaxb-api-test/pom.xml, jaxb-api/pom.xml, pom.xml
=> Integrate activation 2.0.1,

jaxb-api/src/main/java/jakarta/xml/bind/ContextFinder.java, jaxb-api/src/main/java/jakarta/xml/bind/ModuleUtil.java, jaxb-api/src/main/mr-jar/jakarta/xml/bind/ModuleUtil.java
=> #172: default factory class name

jaxb-api/src/main/java/jakarta/xml/bind/ContextFinder.java
=> #121: ContextFinder falls back to context classloader resulting in class cast errors

jaxb-api/src/main/java/jakarta/xml/bind/ContextFinder.java
=> Be defensive when working with passed in classes

jaxb-api/src/main/java/jakarta/xml/bind/ContextFinder.java
=> use class classloader if it has not been loaded by system classloader

.travis.yml
I works by default with JDK 17. I have updated travis to use latest JDK.
=> JDK17 support

jaxb-api-test/pom.xml, jaxb-api/pom.xml, pom.xml, spec/pom.xml
=> bump project version to 4.0.0-SNAPSHOT

.github/workflows/maven.yml
Signed-off-by: Tomas Kraus <tomas.kraus@oracle.com>
=> Maven build renamed.

api/src/main/java/jakarta/xml/bind/annotation/adapters/XmlJavaTypeAdapter.java
Signed-off-by: Tomas Kraus <tomas.kraus@oracle.com>
=> Simplified generics in XmlJavaTypeAdapter.

pom.xml
=> integrate activation 2.1.0

api/pom.xml, api/src/main/java/jakarta/xml/bind/Binder.java, api/src/main/java/jakarta/xml/bind/ContextFinder.java, api/src/main/java/jakarta/xml/bind/DatatypeConverterImpl.java, api/src/main/java/jakarta/xml/bind/DatatypeConverterInterface.java, api/src/main/java/jakarta/xml/bind/JAXB.java, api/src/main/java/jakarta/xml/bind/JAXBPermission.java, api/src/main/java/jakarta/xml/bind/Marshaller.java, api/src/main/java/jakarta/xml/bind/Unmarshaller.java, api/src/main/java/jakarta/xml/bind/ValidationEvent.java, api/src/main/java/jakarta/xml/bind/ValidationEventHandler.java, api/src/main/java/jakarta/xml/bind/ValidationEventLocator.java, api/src/main/java/jakarta/xml/bind/annotation/XmlElement.java, api/src/main/java/jakarta/xml/bind/annotation/XmlElementDecl.java, api/src/main/java/jakarta/xml/bind/annotation/XmlElementRef.java, api/src/main/java/jakarta/xml/bind/annotation/XmlInlineBinaryData.java, api/src/main/java/jakarta/xml/bind/annotation/XmlMimeType.java, api/src/main/java/jakarta/xml/bind/annotation/XmlSchema.java, api/src/main/java/jakarta/xml/bind/annotation/XmlSchemaType.java, api/src/main/java/jakarta/xml/bind/annotation/XmlType.java, api/src/main/java/jakarta/xml/bind/annotation/adapters/XmlJavaTypeAdapter.java, api/src/main/java/jakarta/xml/bind/annotation/package-info.java, api/src/main/java/jakarta/xml/bind/attachment/package-info.java, api/src/main/java/jakarta/xml/bind/package-info.java, etc/spotbugs-exclude.xml, pom.xml, spec/src/main/asciidoc/ch04-binding_framework.adoc, spec/src/main/asciidoc/ch08-java_types.adoc
* filter out spotbugs warnings
* remove redundant modifiers
* remove obsolete/unused code
* update build plugins
=> Fix javadoc errors and warnings

api/src/main/java/jakarta/xml/bind/ContextFinder.java, api/src/main/java/jakarta/xml/bind/ServiceLoaderUtil.java
See https://github.com/eclipse-ee4j/eclipselink/issues/1380
Signed-off-by: arjantijms <arjan.tijms@gmail.com>
=> Try multiple providers from OSGi until first succeeds.

CONTRIBUTING.md, NOTICE.md, README.md, api/pom.xml, api/src/main/java/jakarta/xml/bind/ContextFinder.java, api/src/main/java/jakarta/xml/bind/ServiceLoaderUtil.java, etc/jenkins/continuous.groovy, etc/jenkins/release.groovy, etc/spotbugs-exclude.xml, jaxb-api-test/pom.xml, pom.xml
=> fix cpright

etc/jenkins/release.sh, etc/scripts/nexus.incl.sh
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
=> Jenkins release job update

api/src/main/java/jakarta/xml/bind/ContextFinder.java, api/src/main/java/jakarta/xml/bind/JAXBContext.java, spec/src/main/asciidoc/appI-changelog.adoc, spec/src/main/asciidoc/ch04-binding_framework.adoc
=> added impl lookup through properties passed to JAXBContext.newInstance

api/src/main/java/jakarta/xml/bind/ContextFinder.java, api/src/main/java/jakarta/xml/bind/ModuleUtil.java
fixes #224 and prevents possible NPE
=> #224: ModelUtil error in JAXBContext.newInstance()

.github/workflows/maven.yml, pom.xml, spec/pom.xml
* update build plugins
* update GH action build
* update repo org in poms
=> integrate activation-api 2.1.3, parent 1.0.9

api/src/main/java/jakarta/xml/bind/annotation/XmlAttachmentRef.java, api/src/main/java/jakarta/xml/bind/attachment/AttachmentMarshaller.java, api/src/main/java/jakarta/xml/bind/attachment/AttachmentUnmarshaller.java, api/src/main/java/jakarta/xml/bind/attachment/package-info.java, spec/src/main/asciidoc/appA-references.adoc
@lukasj 
I wish this commit would be useful for the project.
Regards,
Antonio.
=> update ws-i links marked in #236

api/src/main/java/jakarta/xml/bind/DatatypeConverterImpl.java, api/src/test/java/org/eclipse/jaxb/api/DatatypeConverterTest.java
@lukasj
I wish this commit would be useful for the project.
Regards,
Antonio.
=> fix #229 including tests
